export let  EventName =
{
    move :"move",
    GameStart :"GameStart",




    CLIENT_GAME_LOGIN_SUCC:"CLIENT_GAME_LOGIN_SUCC",
    CLIENT_GAME_LOGIN_FAILED:"CLIENT_GAME_LOGIN_FAILED",

    OTHER_PLAYER_MOVE:"OTHER_PLAYER_MOVE",
    CLIENT_GAME_START:"CLIENT_GAME_START", //玩家满了

    CLIENT_GAME_SHOW_START:"CLIENT_GAME_SHOW_START", //游戏内界面显示


    CLIENT_SHOW_TIPS:"CLIENT_SHOW_TIPS",
    CLIENT_HIDE_TIPS:"CLIENT_HIDE_TIPS"
}