export let  EventName =
{
    move :"move",
    GameStart :"GameStart",




    CLIENT_GAME_LOGIN_SUCC:"CLIENT_GAME_LOGIN_SUCC",
    CLIENT_GAME_LOGIN_FAILED:"CLIENT_GAME_LOGIN_FAILED",

    OTHER_PLAYER_MOVE:"OTHER_PLAYER_MOVE",
    CLIENT_GAME_START:"CLIENT_GAME_START",
}